---
- hosts: centos
  tasks:
      - name: install python, pip
        yum:
            name:
                - python3
                - python3-pip
                - python3-setuptools
            state: present
      - name: install virtual_enviroment
        pip:
            executable: /usr/local/bin/pip3
            name: virtual_enviroment
            state: present
      - name: create environment
        pip:
            virtual_enviroment: "{{ venv_path }}"
            virtualenv_command: python3 -m venv
            requirements: "{{ app_path }}/requirements.txt"

- hosts: debian
  tasks:
      - name: install python, pip
        apt:
            name:
                - python3
                - python3-pip
                - python3-setuptools
            state: present
      - name: install virtual_enviroment
        pip:
            executable: pip3
            name: virtual_enviroment
            state: present
      - name: create environment
        pip:
            virtual_enviroment: "{{ venv_path }}"
            virtualenv_command: python3 -m venv
            requirements: "{{ app_path }}/requirements.txt"
