---
- hosts: debian
  tasks:
      - name: install nginx
        apt:
            name: nginx
            state: present
- hosts: centos
  tasks:
      - name: install nginx
        yum:
            name: nginx
            state: present
- hosts: all
  tasks:
      - name: start nginx
        service:
            name: nginx
            state: started
